export const GET_AVAILABILITIES = "GET_AVAILABILITIES";
export const GET_AVAILABILITIES_SUCCESS = "GET_AVAILABILITIES_SUCCESS";
export const GET_AVAILABILITIES_FAIL = "GET_AVAILABILITIES_FAIL";

export const GET_POST_DETAILS = "GET_POST_DETAILS";
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS";
export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL";

export const SELECTED_DATE = "SELECTED_DATE";

export const PREV_DATE_SELECTED = "PREV_DATE_SELECTED";
export const GET_SCHEDULER_TYPES = "GET_SCHEDULER_TYPES";
export const GET_SCHEDULER_TYPES_SUCCESS = "GET_SCHEDULER_TYPES_SUCCESS";
export const GET_SCHEDULER_TYPES_FAIL = "GET_SCHEDULER_TYPES_FAIL";

export const SELECTED_SLOT_DETAILS = "SELECTED_SLOT_DETAILS";