export const GET_AVAILABILITIES = "GET_AVAILABILITIES";
export const GET_AVAILABILITIES_SUCCESS = "GET_AVAILABILITIES_SUCCESS";
export const GET_AVAILABILITIES_FAIL = "GET_AVAILABILITIES_FAIL";

export const GET_POST_DETAILS = "GET_POST_DETAILS";
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS";
export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL";

export const SELECTED_DATE = "SELECTED_DATE";

export const PREV_DATE_SELECTED = "PREV_DATE_SELECTED";