export const GET_AVAILABILITIES = "GET_AVAILABILITIES";
export const GET_AVAILABILITIES_SUCCESS = "GET_AVAILABILITIES_SUCCESS";
export const GET_AVAILABILITIES_FAIL = "GET_AVAILABILITIES_FAIL";

export const PREV_DATE_SELECTED = "PREV_DATE_SELECTED";
export const GET_SCHEDULER_TYPES = "GET_SCHEDULER_TYPES";
export const GET_SCHEDULER_TYPES_SUCCESS = "GET_SCHEDULER_TYPES_SUCCESS";
export const GET_SCHEDULER_TYPES_FAIL = "GET_SCHEDULER_TYPES_FAIL";

export const SELECTED_SLOT_DETAILS = "SELECTED_SLOT_DETAILS";

export const BOOK_SLOT = "BOOK_SLOT";
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SLOT";
export const BOOK_SLOT_FAIL = "BOOK_SLOT_FAIL";

export const SELECTED_TYPE_DETAILS = "SELECTED_TYPE_DETAILS";

export const CLEAR_AVAILABILITIES = "CLEAR_AVAILABILITIES";

export const CLEAR_BOOKED_SLOTS = "CLEAR_BOOKED_SLOTS";

export const SET_USER_SESSION_DETAILS = "SET_USER_SESSION_DETAILS";

export const CLEAR_USER_SESSION_DETAILS = "CLEAR_USER_SESSION_DETAILS";

export const MY_BOOKINGS = "MY_BOOKINGS";
export const MY_BOOKINGS_SUCCESS = "MY_BOOKINGS_SUCCESS";
export const MY_BOOKINGS_FAIL = "MY_BOOKINGS_FAIL";

export const SELECTED_RESCHEDULER_DETAILS = "SELECTED_RESCHEDULER_DETAILS";

export const CANCEL_SLOT = "CANCEL_SLOT";
export const CANCEL_SLOT_SUCCESS = "CANCEL_SLOT_SUCCESS";
export const CANCEL_SLOT_FAIL = "CANCEL_SLOT_FAIL";

export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

export const CLEAR_CANCEL_SLOTS = "CLEAR_CANCEL_SLOTS";

export const SELECTED_PROFILE_OPTION = "SELECTED_PROFILE_OPTION";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const IS_SIGNED_IN = "IS_SIGNED_IN";

