export const GET_AVAILABILITIES = "GET_AVAILABILITIES";
export const GET_AVAILABILITIES_SUCCESS = "GET_AVAILABILITIES_SUCCESS";
export const GET_AVAILABILITIES_FAIL = "GET_AVAILABILITIES_FAIL";

export const PREV_DATE_SELECTED = "PREV_DATE_SELECTED";
export const GET_SCHEDULER_TYPES = "GET_SCHEDULER_TYPES";
export const GET_SCHEDULER_TYPES_SUCCESS = "GET_SCHEDULER_TYPES_SUCCESS";
export const GET_SCHEDULER_TYPES_FAIL = "GET_SCHEDULER_TYPES_FAIL";

export const SELECTED_SLOT_DETAILS = "SELECTED_SLOT_DETAILS";

export const BOOK_SLOT = "BOOK_SLOT";
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SLOT";
export const BOOK_SLOT_FAIL = "BOOK_SLOT_FAIL";

export const SELECTED_TYPE_DETAILS = "SELECTED_TYPE_DETAILS";

export const CLEAR_AVAILABILITIES = "CLEAR_AVAILABILITIES";

export const CLEAR_BOOKED_SLOTS = "CLEAR_BOOKED_SLOTS";